package com.fooddelivery.order.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Ensures legacy PostgreSQL check constraints generated by older Hibernate versions
 * (such as orders_status_check) are automatically dropped so new OrderStatus enum values
 * (e.g., PENDING_PAYMENT, PAID, PAYMENT_FAILED) can be inserted without constraint violations.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DatabaseSchemaInitializer implements ApplicationRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(ApplicationArguments args) {
        try {
            log.info("Updating database schema constraints for 'orders' table...");
            jdbcTemplate.execute("ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check");
            jdbcTemplate.execute("ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_payment_status_check");
            log.info("Successfully ensured 'orders_status_check' and 'orders_payment_status_check' constraints are removed.");
        } catch (Exception e) {
            log.warn("Could not drop constraints on orders table: {}", e.getMessage());
        }

    }
}
