server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/auth/**
          - id: order-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/orders/**
          - id: restaurant-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/restaurants/**
          - id: delivery-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/deliveries/**
          - id: payment-service
            uri: http://localhost:8085
            predicates:
              - Path=/api/payments/**
          - id: auth-service-docs
            uri: http://localhost:8081
            predicates:
              - Path=/auth-docs/**
            filters:
              - StripPrefix=1
          - id: order-service-docs
            uri: http://localhost:8082
            predicates:
              - Path=/order-docs/**
            filters:
              - StripPrefix=1
          - id: restaurant-service-docs
            uri: http://localhost:8083
            predicates:
              - Path=/restaurant-docs/**
            filters:
              - StripPrefix=1
          - id: delivery-service-docs
            uri: http://localhost:8084
            predicates:
              - Path=/delivery-docs/**
            filters:
              - StripPrefix=1
          - id: payment-service-docs
            uri: http://localhost:8085
            predicates:
              - Path=/payment-docs/**
            filters:
              - StripPrefix=1

# Springdoc / Swagger Aggregator Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-operation-id: true
    default-models-expand-depth: 1
    doc-expansion: list
    urls:
      - name: 1. Auth Service (8081)
        url: /auth-docs/v3/api-docs
      - name: 2. Order Service (8082)
        url: /order-docs/v3/api-docs
      - name: 3. Restaurant Service (8083)
        url: /restaurant-docs/v3/api-docs
      - name: 4. Delivery Service (8084)
        url: /delivery-docs/v3/api-docs
      - name: 5. Payment Service (8085)
        url: /payment-docs/v3/api-docs
